name: procedure_ui
description: UI components for the Procedure application.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "3.32.5"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0
  go_router: ^16.2.4
  file_picker: ^10.3.3
  flutter_svg: ^2.2.1
  yaml: ^3.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.2
  rlm:
    path: ../../flutter/rust_builder
  flutter_rust_bridge: ^2.11.1
  freezed_annotation: ^3.1.0
  http: ^1.3.0
  firebase_core: ^4.1.1
  firebase_ai: ^3.3.0
  firebase_auth: ^6.1.0
  firebase_ui_auth: ^3.0.0
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^2.0.0
  cloud_functions: ^6.0.2
  procedure_bindings:
    path: ../procedure_bindings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.2.3

flutter:
  uses-material-design: true
