[package]
name = "rust_lib_metasampler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
serde_json = "1.0"
cmajor-rs = { path = "../../../cmajor-rs" }