[package]
name = "audio-plugin-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
# tonevision-types = { path = "../../lib/types" }

[build-dependencies]
cmake = "0.1"

[lib]
crate-type = ["rlib", "staticlib"]
