name: procedure_bindings
description: Generated flutter_rust_bridge bindings for Procedure.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_rust_bridge: ^2.11.1
